print("test numero dos tres quatro bep bep bep bep beeeep bep bep")
print("test numero dos tres quatro bep bep bep bep beeeep bep bep")
print("test numero dos tres quatro bep bep bep bep beeeep bep bep be be bep bep bep bep bep bep bep bep")
print("test numero dos tres quatro bep bep bep bep beeeep bep bep be be bep bep bep bep bep bep bep bep")
print("test numero dos tres quatro bep bep bep bep beeeep bep bep be be bep bep bep bep bep bep bep bep")
print("test numero dos tres quatro bep bep bep bep beeeep bep bep be be bep bep bep bep bep bep bep bep")
print("test numero dos tres quatro bep bep bep bep beeeep bep bep be be bep bep bep bep bep bep bep bep")
print("test numero dos tres quatro bep bep bep bep beeeep bep bep be be bep bep bep bep bep bep bep bep")
print("test numero dos tres quatro bep bep bep bep beeeep bep bep be be bep bep bep bep bep bep bep bep")
print("oh how much I want to work")
print("I am the best employee")
